version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: tech-events-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tech_events_db
    ports:
      - "5432:5432"
    volumes:
      - tech-events-data:/var/lib/postgresql/data

volumes:
  tech-events-data:
